Refactor admin dashboard and implement admin login page
dr-Ariawan-s-Project/web-drariawan pull request #21
Opened 2023-09-14 06:02 UTC by Almiramahsa

minta tolong untuk di review @BagasDhitya

2023-09-14 07:57 UTC, bagasdhitya98 commented on src/routes/App.tsx
> +        <Route element={<AdminLogin />} path="admin-login" />
penamaan pathnya minta tolong disesuaikan lagi, soalnya disini ndak ada yang pakai simbol dash mir hehehe @Almiramahsa

2023-09-14 08:01 UTC, bagasdhitya98 commented on src/components/LoginForm.tsx
> +import { useForm } from 'react-hook-form';
ini kita mau pakai react hook form atau formik? aku soale udah pake formik buat di user form component

2023-09-14 08:01 UTC, bagasdhitya98 commented on package.json
> +    "validator": "^13.11.0",
validator ini buat apa?

2023-09-14 08:02 UTC, bagasdhitya98 commented on package.json
> +    "lottie-react": "^2.4.0",
lottie-react ini buat apa?

2023-09-14 08:03 UTC, bagasdhitya98 reviewed
masih ada beberapa yang perlu disesuaikan, terutama terkait penggunaan library

cc : @Almiramahsa

2023-09-14 08:04 UTC, bagasdhitya98 requested changes
masih ada beberapa perlu penyesuaian terkait library, comment nya bisa dicek di commit yak

cc : @Almiramahsa

2023-09-14 08:58 UTC, Almiramahsa commented on package.json
> +    "validator": "^13.11.0",
nggak jadi pake validator mas, aku uninstall nanti

2023-09-14 08:58 UTC, Almiramahsa commented on package.json
> +    "lottie-react": "^2.4.0",
lottie ini untuk animasi mas, untuk gerak2in gambar

2023-09-14 08:59 UTC, Almiramahsa commented on src/routes/App.tsx
> +        <Route element={<AdminLogin />} path="admin-login" />
oke mas, aku sesuaikan lagi untuk penamaan pathnya

2023-09-15 02:51 UTC, bagasdhitya98 approved these changes

2023-09-15 02:57 UTC, merged